version: '2.4'
services:
  bhclear:
    image: bluehelixnetwork/testnet:v0.1.0
    entrypoint: [ "bhd", "start", "--minimum-gas-prices", "1ubht" ]
    depends_on:
      - chainnode
    ports:
      - "26656-26657:26656-26657"
    volumes:
      - ./data/bhd:/root/.bhd
    network_mode: host

  bhcli:
    image: bluehelixnetwork/testnet:v0.1.0
    entrypoint: [ "bhcli" ]
    volumes:
      - ./data/bhcli:/root/.bhcli
    network_mode: host

  chainnode:
    image: bluehelixnetwork/testnet-chainnode:v0.1.0
    ports:
      - "8888:8888"
    network_mode: host
